version: '3'

services:
  laravel:
    build: 
      context: ./laravel
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "80:80"

networks:
  laranet:
    driver: bridge